---
- hosts: all

  tasks:
  - include: casks.yml
  - include: formulas.yml

  roles:

  # osx config
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # dev
  - role: git
    git_user_name: Cristian
    git_user_email: me@cristian.io
  - role: legit
  - role: hub
