---
- hosts: all
  roles:

  # osx config
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # dev
  - role: git
    git_user_name: Cristian
    git_user_email: me@cristian.io
  - role: legit
  - role: hub
  - role: brew_package
    package_name: mongodb
  - role: brew_package
    package_name: sbt
  - role: cask_package
    package_name: slack
  - role: cask_package
    package_name: appdelete
  - role: cask_package
    package_name: intellij-idea
  - role: cask_package
    package_name: spotify
  - role: cask_package
    package_name: dash
  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  ## fun
  - role: brew_package
    package_name: fortune
  - role: brew_package
    package_name: cowsay
